import { test, expect } from '@playwright/test';

/**
 * MediaHub BrandedLoader (converted BrandedLoader.tsx) — regression check.
 *
 * Based on QA report (mediahub-brandedloader pair, verdict: match).
 *
 * Behavior in test environment:
 * - With the test Clerk key (`pk_test_Y2xlcmsuZXhhbXBsZS5jb20k`) in a
 *   headless browser, Clerk's `useUser().isLoaded` stays `false` indefinitely.
 * - PrivateRoute renders <BrandedLoader message="Securing your session and
 *   loading MediaHub" /> while `!isLoaded` — so the loader stays visible
 *   rather than redirecting to /sign-in.
 * - This is expected test-environment behavior, not an app bug.
 *
 * Tests verify:
 * 1. The BrandedLoader component renders the correct message text.
 * 2. All three animated dot elements have the correct CSS classes.
 * 3. Protected routes consistently show the loader (no JS crash).
 * 4. The component is visible on multiple distinct protected routes,
 *    confirming no regression from the TypeScript conversion.
 */
test.describe('BrandedLoader (TypeScript conversion regression check)', () => {
  test('navigating to /docs shows BrandedLoader with correct message', async ({ page }) => {
    await page.goto('/docs');
    // BrandedLoader renders while Clerk isLoaded=false; wait for the message
    await expect(
      page.getByText('Securing your session and loading MediaHub')
    ).toBeVisible({ timeout: 5000 });
  });

  test('navigating to /video-streaming shows BrandedLoader', async ({ page }) => {
    await page.goto('/video-streaming');
    await expect(
      page.getByText('Securing your session and loading MediaHub')
    ).toBeVisible({ timeout: 5000 });
  });

  test('navigating to /media shows BrandedLoader', async ({ page }) => {
    await page.goto('/media');
    await expect(
      page.getByText('Securing your session and loading MediaHub')
    ).toBeVisible({ timeout: 5000 });
  });

  test('BrandedLoader renders all three animated dot elements', async ({ page }) => {
    await page.goto('/docs');
    await page.waitForSelector('text=Securing your session and loading MediaHub', {
      timeout: 5000,
    });
    // Dots generated by BrandedLoader.tsx: .loader-dot-1/.loader-dot-2/.loader-dot-3
    await expect(page.locator('.loader-dot-1')).toBeAttached();
    await expect(page.locator('.loader-dot-2')).toBeAttached();
    await expect(page.locator('.loader-dot-3')).toBeAttached();
  });

  test('BrandedLoader renders "MediaHub" brand text alongside the icon', async ({ page }) => {
    await page.goto('/docs');
    await page.waitForSelector('text=Securing your session and loading MediaHub', {
      timeout: 5000,
    });
    // The h2 inside BrandedLoader contains "MediaHub" brand text
    await expect(page.getByRole('heading', { name: 'MediaHub', level: 2 })).toBeVisible();
  });
});
